# Generated by Django 4.2.17 on 2026-05-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工艺名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('unit', models.CharField(choices=[('area', '面积(dm²)'), ('weight', '重量(kg)'), ('piece', '件数')], default='area', max_length=10, verbose_name='计费单位')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础单价')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '镀种工艺',
                'verbose_name_plural': '镀种工艺',
                'db_table': 'plating_processes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单价')),
                ('min_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低收费')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, help_text='留空表示通用定价', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
                ('plating_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.platingprocess', verbose_name='镀种工艺')),
            ],
            options={
                'verbose_name': '计费规则',
                'verbose_name_plural': '计费规则',
                'db_table': 'pricing_rules',
                'ordering': ['-effective_date'],
            },
        ),
    ]
