# Generated by Django 4.2.17 on 2026-05-19 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_spec', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待加工'), ('processing', '加工中'), ('completed', '已完工'), ('shipped', '已出货')], default='pending', max_length=20, verbose_name='状态')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='来料日期')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='完工日期')),
                ('shipped_at', models.DateField(blank=True, null=True, verbose_name='出货日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='客户')),
                ('plating_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.platingprocess', verbose_name='镀种工艺')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
