# Generated by Django 4.2.17 on 2026-05-20 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_no', models.CharField(max_length=20, unique=True, verbose_name='应付单号')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商')),
                ('category', models.CharField(choices=[('material', '原料'), ('electricity', '电费'), ('equipment', '设备'), ('other', '其他')], default='material', max_length=20, verbose_name='类别')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应付总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
                ('status', models.CharField(choices=[('open', '未付'), ('partial', '部分付款'), ('settled', '已结清')], default='open', max_length=10, verbose_name='状态')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '应付账款',
                'verbose_name_plural': '应付账款',
                'db_table': 'payables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable_no', models.CharField(max_length=20, unique=True, verbose_name='应收单号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应收总额')),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已收金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
                ('status', models.CharField(choices=[('open', '未结'), ('partial', '部分回款'), ('settled', '已结清')], default='open', max_length=10, verbose_name='状态')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '应收账款',
                'verbose_name_plural': '应收账款',
                'db_table': 'receivables',
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=20, unique=True, verbose_name='流水号')),
                ('type', models.CharField(choices=[('receive', '收款'), ('pay', '付款')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('payment_method', models.CharField(choices=[('transfer', '银行转账'), ('cash', '现金'), ('acceptance', '承兑汇票')], default='transfer', max_length=20, verbose_name='支付方式')),
                ('payment_date', models.DateField(verbose_name='支付日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='客户')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.payable', verbose_name='关联应付')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.receivable', verbose_name='关联应收')),
            ],
            options={
                'verbose_name': '收付款记录',
                'verbose_name_plural': '收付款记录',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
