# Generated by Django 4.2.17 on 2026-05-20 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_no', models.CharField(max_length=20, unique=True, verbose_name='对账单号')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='合计金额')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='调整金额')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最终金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('sent', '已发送')], default='draft', max_length=10, verbose_name='状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_statements', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='客户')),
                ('orders', models.ManyToManyField(blank=True, to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '月度对账单',
                'verbose_name_plural': '月度对账单',
                'db_table': 'monthly_statements',
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
    ]
