# Generated by Django 4.2.17 on 2026-05-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='材料费')),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='电费')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='人工费')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他费用')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总成本')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='利润')),
                ('profit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='利润率(%)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单成本',
                'verbose_name_plural': '订单成本',
                'db_table': 'order_costs',
            },
        ),
    ]
