# Generated by Django 4.2.17 on 2026-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='简称')),
                ('contact_person', models.CharField(blank=True, max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('payment_terms', models.IntegerField(default=30, help_text='如30/60/90', verbose_name='月结天数')),
                ('default_billing_type', models.CharField(choices=[('area', '按面积(dm²)'), ('weight', '按重量(kg)'), ('piece', '按件数')], default='area', max_length=10, verbose_name='默认计费方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
